version: '3.8'

services:
  drms-server:
    image: drms/server:latest
    ports:
      - "8000:8000"
    environment:
      - DRMS_API_HOST=0.0.0.0
      - DRMS_API_PORT=8000
      - DRMS_LOG_LEVEL=INFO
      - DRMS_VECTOR_DB_PATH=/app/data/chroma_db
      - DRMS_CACHE_DIR=/app/data/cache
    volumes:
      - drms_data:/app/data
      - drms_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - drms_ssl:/etc/ssl/certs
    depends_on:
      - drms-server
    restart: unless-stopped

volumes:
  drms_data:
    driver: local
  drms_logs:
    driver: local
  drms_ssl:
    driver: local

networks:
  default:
    name: drms-network